#!/usr/bin/env ruby -U

USERNAME = "makevoid"

# training:

# "example == esempio"
# "react.rb" == "react ruby"

# "react" ~= "react.rb"


DEPENDENCIES = [
  "git bitcoin opal",
  "ruby",
  # "esempio bitcoin blockchain react",
  # "esempio bitcoin bitstamp react",
]

##

def username
  USERNAME
end

def dependencies
  DEPENDENCIES
end

##

# search github

# module
def ex(arg)
  p `#{arg}`
end

def install(project_name:)
  ex "cd ~/tmp"
  ex "rm -rf ~/tmp/"
  ex "git clone #{username}/#{project_name}"
end

def main
  dependencies.each do |dep|
    install project_name: dep
  end
end

def try_all_apps
  apps.each do |app|
    try_run_app app
  end
end

def try_run_app
  expect "server running"
  # expect "read apis and try to call them"
end

##

main
